export const tours = [
    {
      heading: 'Mountains',
      text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.',
      image: 'assets/mountain.jpg',
      date: '20.02.2020',
      time: '20:00',
      quote:'The silence is incredible!',
      place: 'Apalachen',
    },
    {
      heading: 'Boattrip',
      text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.',
      image: 'assets/boat.jpg',
      date: '02.08.2020',
      time: '13:53',
      quote:'The sunsets are awesome',
      place: 'Pacific ocean',
    },
    {
      heading: 'New York',
      text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.',
      image: 'assets/city.jpg',
      date: '14.03.2019',
      time: '04:35',
      quote:'Like in the movies!',
      place: 'New York',
    },
    {
      heading: 'Desert',
      text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.',
      image: 'assets/desert.jpg',
      date: '12.06.2018',
      time: '19:20',
      quote:'Everybody loves them',
      place: 'Berlin',
    },
    {
      heading: 'Maledives',
      text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.',
      image: 'assets/beach.jpg',
      date: '15.09.2020',
      time: '12:10',
      quote:'Sun and freedom',
      place: 'Maledivs',
    },
    {
      heading: 'Venice',
      text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.',
      image: 'assets/venice.jpg',
      date: '01.10.2020',
      time: '09:35',
      quote:'I will never forget this',
      place: 'Vienna',
    },
  ];
  